language: php
php:
        - '5.5'
        - '5.6'
        - '7.0'
        - hhvm
        - nightly

before_script:
        - cp .env.travis .env
        - rm phpunit.xml
        - cp phpunit.xml.travis phpunit.xml
        - mysql -e 'create database travis_testing;'
        - composer self-update
        - composer install --no-interaction

script: 
        - composer install
        - vendor/bin/phpunit
